Game.AddToInventory("Items.Cop_01_Set_Boots",1)
Game.AddToInventory("Items.Cop_01_Set_Glasses",1)
Game.AddToInventory("Items.Cop_01_Set_Jacket",1)
Game.AddToInventory("Items.Cop_01_Set_Pants",1)
Game.AddToInventory("Items.Corporate_01_Set_FormalJacket",1)
Game.AddToInventory("Items.Corporate_01_Set_FormalShirt",1)
Game.AddToInventory("Items.Corporate_01_Set_FormalShoes",1)
Game.AddToInventory("Items.Corporate_01_Set_Glasses",1)
Game.AddToInventory("Items.Corporate_01_Set_Pants",1)
Game.AddToInventory("Items.Fixer_01_Set_Coat",1)
Game.AddToInventory("Items.Fixer_01_Set_FormalShoes",1)
Game.AddToInventory("Items.Fixer_01_Set_Glasses",1)
Game.AddToInventory("Items.Fixer_01_Set_Pants",1)
Game.AddToInventory("Items.Fixer_01_Set_TShirt",1)
Game.AddToInventory("Items.Media_01_Set_Cap",1)
Game.AddToInventory("Items.Media_01_Set_Pants",1)
Game.AddToInventory("Items.Media_01_Set_Shirt",1)
Game.AddToInventory("Items.Media_01_Set_Shoes",1)
Game.AddToInventory("Items.Media_01_Set_Tech",1)
Game.AddToInventory("Items.Media_01_Set_Vest",1)
Game.AddToInventory("Items.Netrunner_01_Set_Jumpsuit",1)
Game.AddToInventory("Items.Netrunner_01_Set_Pants",1)
Game.AddToInventory("Items.Netrunner_01_Set_Shoes",1)
Game.AddToInventory("Items.Netrunner_01_Set_Visor",1)
Game.AddToInventory("Items.Nomad_01_Set_Boots",1)
Game.AddToInventory("Items.Nomad_01_Set_Jacket",1)
Game.AddToInventory("Items.Nomad_01_Set_Mask",1)
Game.AddToInventory("Items.Nomad_01_Set_Pants",1)
Game.AddToInventory("Items.Nomad_01_Set_TShirt",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Boots",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Glasses",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Jacket",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Pants",1)
Game.AddToInventory("Items.Rockerboy_01_Set_TShirt",1)
Game.AddToInventory("Items.Solo_01_Set_Visor", 1)
Game.AddToInventory("Items.Solo_01_Set_TShirt", 1)
Game.AddToInventory("Items.Solo_01_Set_Pants", 1)
Game.AddToInventory("Items.Solo_01_Set_Jacket", 1)
Game.AddToInventory("Items.Solo_01_Set_Boots", 1)
Game.AddToInventory("Items.Techie_01_Set_Cap",1)
Game.AddToInventory("Items.Techie_01_Set_Pants",1)
Game.AddToInventory("Items.Techie_01_Set_Shoes",1)
Game.AddToInventory("Items.Techie_01_Set_Tech",1)
Game.AddToInventory("Items.Techie_01_Set_TShirt",1)
Game.AddToInventory("Items.Techie_01_Set_Vest",1)
