Game.AddToInventory("Items.Nomad_01_Set_Boots",1)
Game.AddToInventory("Items.Nomad_01_Set_Jacket",1)
Game.AddToInventory("Items.Nomad_01_Set_Mask",1)
Game.AddToInventory("Items.Nomad_01_Set_Pants",1)
Game.AddToInventory("Items.Nomad_01_Set_TShirt",1)