Game.AddToInventory("Items.Rockerboy_01_Set_Boots",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Glasses",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Jacket",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Pants",1)
Game.AddToInventory("Items.Rockerboy_01_Set_TShirt",1)