Game.SetAtt("Strength", 20)
Game.SetAtt("Intelligence", 20)
Game.SetAtt("TechnicalAbility", 20)
Game.SetAtt("Reflexes", 20)
Game.SetAtt("Cool", 20)
Game.SetLevel("StreetCred",50)
Game.SetLevel("Level",50)
Game.AddExp("Assault", 1000000)
Game.AddExp("Athletics", 1000000)
Game.AddExp("Brawling", 1000000)
Game.AddExp("ColdBlood", 1000000)
Game.AddExp("CombatHacking", 1000000)
Game.AddExp("Cool", 1000000)
Game.AddExp("Crafting", 1000000)
Game.AddExp("Demolition", 1000000)
Game.AddExp("Engineering", 1000000)
Game.AddExp("Gunslinger", 1000000)
Game.AddExp("Hacking", 1000000)
Game.AddExp("Hacking", 1000000)
Game.AddExp("Intelligence", 1000000)
Game.AddExp("Kenjutsu", 1000000)
Game.AddExp("Reflexes", 1000000)
Game.AddExp("Stealth", 1000000)
Game.AddExp("Strength", 1000000)
Game.AddExp("TechnicalAbility", 1000000)
Game.GiveDevPoints("Primary", 319)
Game.EnableAllPlayerVehicles()
Game.AddToInventory("Items.AjaxRecipe",1)
Game.AddToInventory("Items.AnimalsStrongArmsBattery1",1)
Game.AddToInventory("Items.AnimalsStrongArmsKnuckles1",1)
Game.AddToInventory("Items.ArasakaEpicMKIII",1)
Game.AddToInventory("Items.ArasakaLegendaryMKIV",1)
Game.AddToInventory("Items.ArasakaLegendaryMKIV",1)
Game.AddToInventory("Items.ArasakaMeleeWeaponMod", 1)
Game.AddToInventory("Items.AshuraRecipe",1)
Game.AddToInventory("Items.BatonRecipe",1)
Game.AddToInventory("Items.BatRecipe",1)
Game.AddToInventory("Items.BioConductorsEpic",1)
Game.AddToInventory("Items.BioConductorsLegendary",1)
Game.AddToInventory("Items.BioConductorsLegendary",1)
Game.AddToInventory("Items.BioConductorsRare",1)
Game.AddToInventory("Items.BioDyneRareMKII",1)
Game.AddToInventory("Items.BioDyneUncommonMKI",1)
Game.AddToInventory("Items.BiotechEpicMKIII",1)
Game.AddToInventory("Items.BiotechRareMKII",1)
Game.AddToInventory("Items.BiotechUncommonMKI",1)
Game.AddToInventory("Items.BlindLvl2Program",1)
Game.AddToInventory("Items.BlindLvl2Program",1)
Game.AddToInventory("Items.BlindLvl3Program",1)
Game.AddToInventory("Items.BlindLvl3Program",1)
Game.AddToInventory("Items.BlindLvl4Program",1)
Game.AddToInventory("Items.BlindLvl4Program",1)
Game.AddToInventory("Items.BlindProgram",1)
Game.AddToInventory("Items.BloodPumpCommon",1)
Game.AddToInventory("Items.BloodPumpEpic",1)
Game.AddToInventory("Items.BloodPumpLegendary",1)
Game.AddToInventory("Items.BloodPumpRare",1)
Game.AddToInventory("Items.BloodPumpUncommon",1)
Game.AddToInventory("Items.BonesMcCoy70V0",1)
Game.AddToInventory("Items.BonesMcCoy70V1",1)
Game.AddToInventory("Items.BonesMcCoy70V2",1)
Game.AddToInventory("Items.BoostedTendonsRare",1)
Game.AddToInventory("Items.BootsRecipe", 1)
Game.AddToInventory("Items.BrainCapacityBoosterEpic",1)
Game.AddToInventory("Items.BrainCapacityBoosterLegendary",1)
Game.AddToInventory("Items.BrainCapacityBoosterRare",1)
Game.AddToInventory("Items.BrainMeltLvl2Program",1)
Game.AddToInventory("Items.BrainMeltLvl3Program",1)
Game.AddToInventory("Items.BrainMeltLvl4Program",1)
Game.AddToInventory("Items.BuryaRecipe",1)
Game.AddToInventory("Items.CapRecipe", 1)
Game.AddToInventory("Items.CarnageRecipe",1)
Game.AddToInventory("Items.CarryCapacityBooster",1)
Game.AddToInventory("Items.CasualShoesRecipe", 1)
Game.AddToInventory("Items.ChaoRecipe",1)
Game.AddToInventory("Items.ChemicalDamageCable",1)
Game.AddToInventory("Items.ChemicalDamageEdge",1)
Game.AddToInventory("Items.ChemicalDamageKnuckles",1)
Game.AddToInventory("Items.ChemicalDamageRound",1)
Game.AddToInventory("Items.CommonMaterial1", 10000000)
Game.AddToInventory("Items.CommsCallInLvl3Program",1)
Game.AddToInventory("Items.CommsCallInLvl3Program",1)
Game.AddToInventory("Items.CommsCallInProgram",1)
Game.AddToInventory("Items.CommsCallInProgram",1)
Game.AddToInventory("Items.CommsNoiseLvl2Program",1)
Game.AddToInventory("Items.CommsNoiseLvl3Program",1)
Game.AddToInventory("Items.CommsNoiseLvl4Program",1)
Game.AddToInventory("Items.CommsNoiseProgram",1)
Game.AddToInventory("Items.ContagionLvl2Program",1)
Game.AddToInventory("Items.ContagionLvl3Program",1)
Game.AddToInventory("Items.ContagionLvl4Program",1)
Game.AddToInventory("Items.ContagionProgram",1)
Game.AddToInventory("Items.Cop_01_Set_Boots",1)
Game.AddToInventory("Items.Cop_01_Set_Glasses",1)
Game.AddToInventory("Items.Cop_01_Set_Jacket",1)
Game.AddToInventory("Items.Cop_01_Set_Pants",1)
Game.AddToInventory("Items.CopperheadRecipe",1)
Game.AddToInventory("Items.Corporate_01_Set_FormalJacket",1)
Game.AddToInventory("Items.Corporate_01_Set_FormalShirt",1)
Game.AddToInventory("Items.Corporate_01_Set_FormalShoes",1)
Game.AddToInventory("Items.Corporate_01_Set_Glasses",1)
Game.AddToInventory("Items.Corporate_01_Set_Pants",1)
Game.AddToInventory("Items.CrusherRecipe",1)
Game.AddToInventory("Items.CyberdeckSplinter",1)
Game.AddToInventory("Items.CyberRotorsCommon",1)
Game.AddToInventory("Items.CyberRotorsEpic",1)
Game.AddToInventory("Items.CyberRotorsLegendary",1)
Game.AddToInventory("Items.CyberRotorsRare",1)
Game.AddToInventory("Items.CyberRotorsUncommon",1)
Game.AddToInventory("Items.DenseMarrowEpic",1)
Game.AddToInventory("Items.DenseMarrowRare",1)
Game.AddToInventory("Items.DenseMarrowUncommon",1)
Game.AddToInventory("Items.DisableCyberwareLvl2Program",1)
Game.AddToInventory("Items.DisableCyberwareLvl2Program",1)
Game.AddToInventory("Items.DisableCyberwareLvl3Program",1)
Game.AddToInventory("Items.DisableCyberwareLvl3Program",1)
Game.AddToInventory("Items.DisableCyberwareLvl3Program",1)
Game.AddToInventory("Items.DisableCyberwareProgram",1)
Game.AddToInventory("Items.DisableCyberwareProgram",1)
Game.AddToInventory("Items.DischargeConnectorEpic",1)
Game.AddToInventory("Items.DischargeConnectorLegendary",1)
Game.AddToInventory("Items.DischargeConnectorRare",1)
Game.AddToInventory("Items.ElectricDamageCable",1)
Game.AddToInventory("Items.ElectricDamageEdge",1)
Game.AddToInventory("Items.ElectricDamageKnuckles",1)
Game.AddToInventory("Items.ElectricDamageRound",1)
Game.AddToInventory("Items.ElectroshockMechanismCommon",1)
Game.AddToInventory("Items.ElectroshockMechanismEpic",1)
Game.AddToInventory("Items.ElectroshockMechanismLegendary",1)
Game.AddToInventory("Items.ElectroshockMechanismUncommon",1)
Game.AddToInventory("Items.EMPOverloadLvl2Program",1)
Game.AddToInventory("Items.EMPOverloadLvl3Program",1)
Game.AddToInventory("Items.EMPOverloadLvl4Program",1)
Game.AddToInventory("Items.EMPOverloadProgram",1)
Game.AddToInventory("Items.EndoskeletonCommon",1)
Game.AddToInventory("Items.EndoskeletonEpic",1)
Game.AddToInventory("Items.EndoskeletonLegendary",1)
Game.AddToInventory("Items.EndoskeletonRare",1)
Game.AddToInventory("Items.EndoskeletonUncommon",1)
Game.AddToInventory("Items.EnhancedBloodVesselsCommon",1)
Game.AddToInventory("Items.EnhancedBloodVesselsEpic",1)
Game.AddToInventory("Items.EnhancedBloodVesselsLegendary",1)
Game.AddToInventory("Items.EnhancedBloodVesselsRare",1)
Game.AddToInventory("Items.EnhancedBloodVesselsUncommon",1)
Game.AddToInventory("Items.EnhancedTissueCommon",1)
Game.AddToInventory("Items.EnhancedTissueEpic",1)
Game.AddToInventory("Items.EnhancedTissueLegendary",1)
Game.AddToInventory("Items.EnhancedTissueRare",1)
Game.AddToInventory("Items.EnhancedTissueUncommon",1)
Game.AddToInventory("Items.EpicBatRecipe",1)
Game.AddToInventory("Items.EpicBootsRecipe", 1)
Game.AddToInventory("Items.EpicCarnageRecipe",1)
Game.AddToInventory("Items.EpicCasualShoesRecipe", 1)
Game.AddToInventory("Items.EpicChaoRecipe",1)
Game.AddToInventory("Items.EpicFormalPantsRecipe", 1)
Game.AddToInventory("Items.EpicFormalShoesRecipe", 1)
Game.AddToInventory("Items.EpicGlassesRecipe", 1)
Game.AddToInventory("Items.EpicGradRecipe",1)
Game.AddToInventory("Items.EpicHatRecipe", 1)
Game.AddToInventory("Items.EpicKenshinRecipe",1)
Game.AddToInventory("Items.EpicMasamuneRecipe",1)
Game.AddToInventory("Items.EpicMaterial1", 10000000)
Game.AddToInventory("Items.EpicMaterial2", 10000000)
Game.AddToInventory("Items.EpicOvertureRecipe",1)
Game.AddToInventory("Items.EpicPalicaRecipe",1)
Game.AddToInventory("Items.EpicPantsRecipe", 1)
Game.AddToInventory("Items.EpicPulsarRecipe",1)
Game.AddToInventory("Items.EpicScarfRecipe", 1)
Game.AddToInventory("Items.EpicShirtRecipe", 1)
Game.AddToInventory("Items.EpicShortsRecipe", 1)
Game.AddToInventory("Items.EpicSidewinderRecipe",1)
Game.AddToInventory("Items.EpicSor22Recipe",1)
Game.AddToInventory("Items.EpicTacticianRecipe",1)
Game.AddToInventory("Items.EpicTShirtRecipe", 1)
Game.AddToInventory("Items.EpicYukimuraRecipe",1)
Game.AddToInventory("Items.ExplosiveDamageRound",1)
Game.AddToInventory("Items.FastAccessMemoryCommon",1)
Game.AddToInventory("Items.FastAccessMemoryRare",1)
Game.AddToInventory("Items.FastAccessMemoryUncommon",1)
Game.AddToInventory("Items.FastRotor",1)
Game.AddToInventory("Items.Fixer_01_Set_Coat I",1)
Game.AddToInventory("Items.Fixer_01_Set_FormalShoes",1)
Game.AddToInventory("Items.Fixer_01_Set_Glasses",1)
Game.AddToInventory("Items.Fixer_01_Set_Pants",1)
Game.AddToInventory("Items.Fixer_01_Set_TShirt ",1)
Game.AddToInventory("Items.FormalPantsRecipe", 1)
Game.AddToInventory("Items.FormalShoesRecipe", 1)
Game.AddToInventory("Items.FormalSkirtRecipe", 1)
Game.AddToInventory("Items.FuyutsuiCommonMKI",1)
Game.AddToInventory("Items.FuyutsuiTinkererLegendaryMKIII",1)
Game.AddToInventory("Items.GlassesRecipe", 1)
Game.AddToInventory("Items.GradRecipe",1)
Game.AddToInventory("Items.GroundingPlating",1)
Game.AddToInventory("Items.HatRecipe", 1)
Game.AddToInventory("Items.HealOnKillCommon",1)
Game.AddToInventory("Items.HealOnKillEpic",1)
Game.AddToInventory("Items.HealOnKillLegendary",1)
Game.AddToInventory("Items.HealOnKillUncommon",1)
Game.AddToInventory("Items.HealthMonitorCommon",1)
Game.AddToInventory("Items.HealthMonitorEpic",1)
Game.AddToInventory("Items.HealthMonitorLegendary",1)
Game.AddToInventory("Items.HealthMonitorLegendary",1)
Game.AddToInventory("Items.HealthMonitorRare",1)
Game.AddToInventory("Items.HealthMonitorUncommon",1)
Game.AddToInventory("Items.HeatUsingBooster",1)
Game.AddToInventory("Items.HighChargedBattery",1)
Game.AddToInventory("Items.HighChargedWiresBattery",1)
Game.AddToInventory("Items.ImprovedPerceptionCommon",1)
Game.AddToInventory("Items.ImprovedPerceptionEpic",1)
Game.AddToInventory("Items.ImprovedPerceptionLegendary",1)
Game.AddToInventory("Items.ImprovedPerceptionUncommon",1)
Game.AddToInventory("Items.ImprovedReactionEpic",1)
Game.AddToInventory("Items.ImprovedReactionRare",1)
Game.AddToInventory("Items.ImprovedReactionUncommon",1)
Game.AddToInventory("Items.IronLungsCommon",1)
Game.AddToInventory("Items.IronLungsEpic",1)
Game.AddToInventory("Items.IronLungsLegendary",1)
Game.AddToInventory("Items.IronLungsLegendary",1)
Game.AddToInventory("Items.IronLungsRare",1)
Game.AddToInventory("Items.IronLungsUncommon",1)
Game.AddToInventory("Items.JacketRecipe", 1)
Game.AddToInventory("Items.KenshinRecipe",1)
Game.AddToInventory("Items.KerenzikovCommon",1)
Game.AddToInventory("Items.KerenzikovEpic",1)
Game.AddToInventory("Items.KerenzikovLegendary",1)
Game.AddToInventory("Items.KerenzikovRare",1)
Game.AddToInventory("Items.KerenzikovUncommon",1)
Game.AddToInventory("Items.KiroshiOpticsEpic",1)
Game.AddToInventory("Items.KiroshiOpticsRare",1)
Game.AddToInventory("Items.KnifeRecipe",1)
Game.AddToInventory("Items.LegendaryAchillesRecipe",1)
Game.AddToInventory("Items.LegendaryAjaxRecipe",1)
Game.AddToInventory("Items.LegendaryAshuraRecipe",1)
Game.AddToInventory("Items.LegendaryBatonRecipe",1)
Game.AddToInventory("Items.LegendaryBatRecipe",1)
Game.AddToInventory("Items.LegendaryBootsRecipe", 1)
Game.AddToInventory("Items.LegendaryBuryaRecipe",1)
Game.AddToInventory("Items.LegendaryCapRecipe", 1)
Game.AddToInventory("Items.LegendaryCarnageRecipe",1)
Game.AddToInventory("Items.LegendaryCasualShoesRecipe", 1)
Game.AddToInventory("Items.LegendaryChaoRecipe",1)
Game.AddToInventory("Items.LegendaryCopperheadRecipe",1)
Game.AddToInventory("Items.LegendaryCrusherRecipe",1)
Game.AddToInventory("Items.LegendaryDianRecipe",1)
Game.AddToInventory("Items.LegendaryFormalPantsRecipe", 1)
Game.AddToInventory("Items.LegendaryFormalShoesRecipe", 1)
Game.AddToInventory("Items.LegendaryFormalSkirtRecipe", 1)
Game.AddToInventory("Items.LegendaryGlassesRecipe", 1)
Game.AddToInventory("Items.LegendaryGogglesRecipe", 1)
Game.AddToInventory("Items.LegendaryGradRecipe",1)
Game.AddToInventory("Items.LegendaryHatRecipe", 1)
Game.AddToInventory("Items.LegendaryIglaRecipe",1)
Game.AddToInventory("Items.LegendaryJacketRecipe", 1)
Game.AddToInventory("Items.LegendaryJumpsuitRecipe", 1)
Game.AddToInventory("Items.LegendaryKenshinRecipe",1)
Game.AddToInventory("Items.LegendaryKnifeRecipe",1)
Game.AddToInventory("Items.LegendaryLexingtonRecipe",1)
Game.AddToInventory("Items.LegendaryMasamuneRecipe",1)
Game.AddToInventory("Items.LegendaryMaterial1", 10000000)
Game.AddToInventory("Items.LegendaryMaterial2", 10000000)
Game.AddToInventory("Items.LegendaryNekomataRecipe",1)
Game.AddToInventory("Items.LegendaryNovaRecipe",1)
Game.AddToInventory("Items.LegendaryNueRecipe",1)
Game.AddToInventory("Items.LegendaryOmahaRecipe",1)
Game.AddToInventory("Items.LegendaryOvertureRecipe",1)
Game.AddToInventory("Items.LegendaryPalicaRecipe",1)
Game.AddToInventory("Items.LegendaryPantsRecipe", 1)
Game.AddToInventory("Items.LegendaryPulsarRecipe",1)
Game.AddToInventory("Items.LegendaryQuasarRecipe",1)
Game.AddToInventory("Items.LegendarySaratogaRecipe",1)
Game.AddToInventory("Items.LegendarySataraRecipe",1)
Game.AddToInventory("Items.LegendaryScarfRecipe", 1)
Game.AddToInventory("Items.LegendaryShingenRecipe",1)
Game.AddToInventory("Items.LegendaryShirtRecipe", 1)
Game.AddToInventory("Items.LegendaryShortsRecipe", 1)
Game.AddToInventory("Items.LegendarySidewinderRecipe",1)
Game.AddToInventory("Items.LegendarySor22Recipe",1)
Game.AddToInventory("Items.LegendaryTacticianRecipe",1)
Game.AddToInventory("Items.LegendaryTechRecipe", 1)
Game.AddToInventory("Items.LegendaryTesteraRecipe",1)
Game.AddToInventory("Items.LegendaryTightJumpsuitRecipe", 1)
Game.AddToInventory("Items.LegendaryTShirtRecipe", 1)
Game.AddToInventory("Items.LegendaryUnityRecipe",1)
Game.AddToInventory("Items.LegendaryVestRecipe", 1)
Game.AddToInventory("Items.LegendaryVisorRecipe", 1)
Game.AddToInventory("Items.LegendaryYukimuraRecipe",1)
Game.AddToInventory("Items.LegendaryZhuoRecipe",1)
Game.AddToInventory("Items.LexingtonRecipe",1)
Game.AddToInventory("Items.LimbicSystemEnhancementCommon",1)
Game.AddToInventory("Items.LimbicSystemEnhancementLegendary",1)
Game.AddToInventory("Items.LimbicSystemEnhancementRare",1)
Game.AddToInventory("Items.LocomotionMalfunctionLvl2Program",1)
Game.AddToInventory("Items.LocomotionMalfunctionLvl2Program",1)
Game.AddToInventory("Items.LocomotionMalfunctionLvl3Program",1)
Game.AddToInventory("Items.LocomotionMalfunctionLvl3Program",1)
Game.AddToInventory("Items.LocomotionMalfunctionLvl4Program",1)
Game.AddToInventory("Items.LocomotionMalfunctionLvl4Program",1)
Game.AddToInventory("Items.LocomotionMalfunctionProgram",1)
Game.AddToInventory("Items.LocomotionMalfunctionProgram",1)
Game.AddToInventory("Items.LowChargedBattery",1)
Game.AddToInventory("Items.LowChargedWiresBattery",1)
Game.AddToInventory("Items.MadnessLvl4Program",1)
Game.AddToInventory("Items.MantisBladesEpic",1)
Game.AddToInventory("Items.MantisBladesLegendary",1)
Game.AddToInventory("Items.MantisBladesLegendary",1)
Game.AddToInventory("Items.MasamuneRecipe",1)
Game.AddToInventory("Items.Media_01_Set_Cap ",1)
Game.AddToInventory("Items.Media_01_Set_Pants",1)
Game.AddToInventory("Items.Media_01_Set_Shirt",1)
Game.AddToInventory("Items.Media_01_Set_Shoes",1)
Game.AddToInventory("Items.Media_01_Set_Tech",1)
Game.AddToInventory("Items.Media_01_Set_Vest",1)
Game.AddToInventory("Items.MediumChargedBattery",1)
Game.AddToInventory("Items.MediumChargedWiresBattery",1)
Game.AddToInventory("Items.MemoryBoostCommon",1)
Game.AddToInventory("Items.MemoryBoostEpic",1)
Game.AddToInventory("Items.MemoryBoostRare",1)
Game.AddToInventory("Items.MemoryBoostUncommon",1)
Game.AddToInventory("Items.MemoryReplenishmentEpic",1)
Game.AddToInventory("Items.MemoryReplenishmentLegendary",1)
Game.AddToInventory("Items.MemoryWipeLvl2Program",1)
Game.AddToInventory("Items.MetalCoveredSkin",1)
Game.AddToInventory("Items.MetalPlating",1)
Game.AddToInventory("Items.MicroGeneratorCommon",1)
Game.AddToInventory("Items.MicroGeneratorEpic",1)
Game.AddToInventory("Items.MicroGeneratorLegendary",1)
Game.AddToInventory("Items.MicroGeneratorLegendary",1)
Game.AddToInventory("Items.MicroGeneratorRare",1)
Game.AddToInventory("Items.MicroGeneratorUncommon",1)
Game.AddToInventory("Items.MicroVibrationsGeneratorEpic",1)
Game.AddToInventory("Items.MicroVibrationsGeneratorRare",1)
Game.AddToInventory("Items.MicroVibrationsGeneratorUncommon",1)
Game.AddToInventory("Items.MilitechParaline",1)
Game.AddToInventory("Items.MilitechProjectileLauncherRound1",1)
Game.AddToInventory("Items.NanoWiresLegendary",1)
Game.AddToInventory("Items.NanoWiresLegendary",1)
Game.AddToInventory("Items.NekomataRecipe",1)
Game.AddToInventory("Items.NeoFiberCommon",1)
Game.AddToInventory("Items.NeoFiberEpic",1)
Game.AddToInventory("Items.NeoFiberLegendary",1)
Game.AddToInventory("Items.NeoFiberRare",1)
Game.AddToInventory("Items.NeoFiberUncommon",1)
Game.AddToInventory("Items.NeoplasticPlating",1)
Game.AddToInventory("Items.NervousSystemDischarge",1)
Game.AddToInventory("Items.Netrunner_01_Set_Jumpsuit",1)
Game.AddToInventory("Items.Netrunner_01_Set_Pants",1)
Game.AddToInventory("Items.Netrunner_01_Set_Shoes",1)
Game.AddToInventory("Items.Netrunner_01_Set_Visor",1)
Game.AddToInventory("Items.NetwatchNetdriverLegendaryMKV",1)
Game.AddToInventory("Items.Nomad_01_Set_Boots",1)
Game.AddToInventory("Items.Nomad_01_Set_Jacket",1)
Game.AddToInventory("Items.Nomad_01_Set_Mask",1)
Game.AddToInventory("Items.Nomad_01_Set_Pants",1)
Game.AddToInventory("Items.Nomad_01_Set_TShirt",1)
Game.AddToInventory("Items.NovaRecipe",1)
Game.AddToInventory("Items.NueRecipe",1)
Game.AddToInventory("Items.OmahaRecipe",1)
Game.AddToInventory("Items.OpticalCamoEpic",1)
Game.AddToInventory("Items.OpticalCamoLegendary",1)
Game.AddToInventory("Items.OpticalCamoRare",1)
Game.AddToInventory("Items.OverheatLvl2Program",1)
Game.AddToInventory("Items.OverheatLvl3Program",1)
Game.AddToInventory("Items.OverheatLvl4Program",1)
Game.AddToInventory("Items.OverheatProgram",1)
Game.AddToInventory("Items.OverheatProgram",1)
Game.AddToInventory("Items.OvertureRecipe",1)
Game.AddToInventory("Items.PalicaRecipe",1)
Game.AddToInventory("Items.PantsRecipe", 1)
Game.AddToInventory("Items.PerkPointSkillbook", 10000000)
Game.AddToInventory("Items.PhysicalDamageCable",1)
Game.AddToInventory("Items.PhysicalDamageEdge",1)
Game.AddToInventory("Items.PhysicalDamageKnuckles",1)
Game.AddToInventory("Items.PingLvl2Program",1)
Game.AddToInventory("Items.PingLvl3Program",1)
Game.AddToInventory("Items.PingLvl4Program",1)
Game.AddToInventory("Items.PowerfulFabricEnhancer01", 1)
Game.AddToInventory("Items.PowerfulFabricEnhancer02", 1)
Game.AddToInventory("Items.PowerfulFabricEnhancer03", 1)
Game.AddToInventory("Items.PowerfulFabricEnhancer04", 1)
Game.AddToInventory("Items.PowerfulFabricEnhancer05", 1)
Game.AddToInventory("Items.PowerfulFabricEnhancer06", 1)
Game.AddToInventory("Items.PowerfulFabricEnhancer07", 1)
Game.AddToInventory("Items.PowerfulFabricEnhancer08", 1)
Game.AddToInventory("Items.PowerGripLegendary",1)
Game.AddToInventory("Items.ProjectileLauncher",1)
Game.AddToInventory("Items.ProjectileLauncherEpic",1)
Game.AddToInventory("Items.ProjectileLauncherLegendary",1)
Game.AddToInventory("Items.PulsarRecipe",1)
Game.AddToInventory("Items.QuasarRecipe",1)
Game.AddToInventory("Items.QuickHackCommonMaterial1", 10000000)
Game.AddToInventory("Items.QuickHackEpicMaterial1", 10000000)
Game.AddToInventory("Items.QuickHackLegendaryMaterial1", 10000000)
Game.AddToInventory("Items.QuickHackRareMaterial1", 10000000)
Game.AddToInventory("Items.QuickHackUncommonMaterial1", 10000000)
Game.AddToInventory("Items.RareAjaxRecipe",1)
Game.AddToInventory("Items.RareAshuraRecipe",1)
Game.AddToInventory("Items.RareBatonRecipe",1)
Game.AddToInventory("Items.RareBatRecipe",1)
Game.AddToInventory("Items.RareBootsRecipe", 1)
Game.AddToInventory("Items.RareBuryaRecipe",1)
Game.AddToInventory("Items.RareCapRecipe", 1)
Game.AddToInventory("Items.RareCarnageRecipe",1)
Game.AddToInventory("Items.RareCasualShoesRecipe", 1)
Game.AddToInventory("Items.RareChaoRecipe",1)
Game.AddToInventory("Items.RareCopperheadRecipe",1)
Game.AddToInventory("Items.RareCrusherRecipe",1)
Game.AddToInventory("Items.RareFormalPantsRecipe", 1)
Game.AddToInventory("Items.RareFormalShoesRecipe", 1)
Game.AddToInventory("Items.RareFormalSkirtRecipe", 1)
Game.AddToInventory("Items.RareGlassesRecipe", 1)
Game.AddToInventory("Items.RareGradRecipe",1)
Game.AddToInventory("Items.RareHatRecipe", 1)
Game.AddToInventory("Items.RareJacketRecipe", 1)
Game.AddToInventory("Items.RareKenshinRecipe",1)
Game.AddToInventory("Items.RareKnifeRecipe",1)
Game.AddToInventory("Items.RareLexingtonRecipe",1)
Game.AddToInventory("Items.RareMasamuneRecipe",1)
Game.AddToInventory("Items.RareMaterial1", 10000000)
Game.AddToInventory("Items.RareMaterial2", 10000000)
Game.AddToInventory("Items.RareNekomataRecipe",1)
Game.AddToInventory("Items.RareNovaRecipe",1)
Game.AddToInventory("Items.RareNueRecipe",1)
Game.AddToInventory("Items.RareOmahaRecipe",1)
Game.AddToInventory("Items.RareOvertureRecipe",1)
Game.AddToInventory("Items.RarePalicaRecipe",1)
Game.AddToInventory("Items.RarePantsRecipe", 1)
Game.AddToInventory("Items.RarePulsarRecipe",1)
Game.AddToInventory("Items.RareQuasarRecipe",1)
Game.AddToInventory("Items.RareSaratogaRecipe",1)
Game.AddToInventory("Items.RareSataraRecipe",1)
Game.AddToInventory("Items.RareScarfRecipe", 1)
Game.AddToInventory("Items.RareShingenRecipe",1)
Game.AddToInventory("Items.RareShirtRecipe", 1)
Game.AddToInventory("Items.RareShortsRecipe", 1)
Game.AddToInventory("Items.RareSidewinderRecipe",1)
Game.AddToInventory("Items.RareSor22Recipe",1)
Game.AddToInventory("Items.RareTacticianRecipe",1)
Game.AddToInventory("Items.RareTechRecipe", 1)
Game.AddToInventory("Items.RareTesteraRecipe",1)
Game.AddToInventory("Items.RareTShirtRecipe", 1)
Game.AddToInventory("Items.RareUnityRecipe",1)
Game.AddToInventory("Items.RareVestRecipe", 1)
Game.AddToInventory("Items.RareYukimuraRecipe",1)
Game.AddToInventory("Items.RavenEpicMKIII",1)
Game.AddToInventory("Items.RavenLegendaryMKIV",1)
Game.AddToInventory("Items.Recipe_Baton_Alpha",1)
Game.AddToInventory("Items.Recipe_Baton_Beta",1)
Game.AddToInventory("Items.Recipe_BlindProgram",1)
Game.AddToInventory("Items.Recipe_Butchers_Knife",1)
Game.AddToInventory("Items.Recipe_Chefs_Knife",1)
Game.AddToInventory("Items.Recipe_ChemicalDamageCable",1)
Game.AddToInventory("Items.Recipe_ChemicalDamageEdge",1)
Game.AddToInventory("Items.Recipe_ChemicalDamageKnuckles",1)
Game.AddToInventory("Items.Recipe_ChemicalDamageRound",1)
Game.AddToInventory("Items.Recipe_CommsCallInProgram",1)
Game.AddToInventory("Items.Recipe_CommsCallOutProgram",1)
Game.AddToInventory("Items.Recipe_CommsNoiseProgram",1)
Game.AddToInventory("Items.Recipe_Crowbar_Common",1)
Game.AddToInventory("Items.Recipe_DataMinerProgram",1)
Game.AddToInventory("Items.Recipe_DisableCyberwareProgram",1)
Game.AddToInventory("Items.Recipe_ElectricDamageCable",1)
Game.AddToInventory("Items.Recipe_ElectricDamageEdge",1)
Game.AddToInventory("Items.Recipe_ElectricDamageKnuckles",1)
Game.AddToInventory("Items.Recipe_ElectricDamageRound",1)
Game.AddToInventory("Items.Recipe_EMPOverloadProgram",1)
Game.AddToInventory("Items.Recipe_ExplosiveDamageRound",1)
Game.AddToInventory("Items.Recipe_FastRotor",1)
Game.AddToInventory("Items.Recipe_GrenadeExplodeLvl3Program",1)
Game.AddToInventory("Items.Recipe_HighChargedBattery",1)
Game.AddToInventory("Items.Recipe_HighChargedWiresBattery",1)
Game.AddToInventory("Items.Recipe_Kanabo_Common",1)
Game.AddToInventory("Items.Recipe_Katana_1",1)
Game.AddToInventory("Items.Recipe_Katana_2",1)
Game.AddToInventory("Items.Recipe_Katana_3",1)
Game.AddToInventory("Items.Recipe_Katana_4",1)
Game.AddToInventory("Items.Recipe_Kukri_Common",1)
Game.AddToInventory("Items.Recipe_LocomotionMalfunctionProgram",1)
Game.AddToInventory("Items.Recipe_LowChargedBattery",1)
Game.AddToInventory("Items.Recipe_LowChargedWiresBattery",1)
Game.AddToInventory("Items.Recipe_Machete_Common",1)
Game.AddToInventory("Items.Recipe_MadnessLvl3Program",1)
Game.AddToInventory("Items.Recipe_MalfunctionProgram",1)
Game.AddToInventory("Items.Recipe_MediumChargedBattery",1)
Game.AddToInventory("Items.Recipe_MediumChargedWiresBattery",1)
Game.AddToInventory("Items.Recipe_MetalPlating",1)
Game.AddToInventory("Items.Recipe_NeoplasticPlating",1)
Game.AddToInventory("Items.Recipe_OverheatProgram",1)
Game.AddToInventory("Items.Recipe_OverloadProgram",1)
Game.AddToInventory("Items.Recipe_OverrideAttitudeProgram",1)
Game.AddToInventory("Items.Recipe_PhysicalDamageCable",1)
Game.AddToInventory("Items.Recipe_PhysicalDamageEdge",1)
Game.AddToInventory("Items.Recipe_PhysicalDamageKnuckles",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer01",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer02",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer03",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer04",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer05",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer06",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer07",1)
Game.AddToInventory("Items.Recipe_PowerfulFabricEnhancer08",1)
Game.AddToInventory("Items.Recipe_PowerWeaponMod01",1)
Game.AddToInventory("Items.Recipe_PowerWeaponMod02",1)
Game.AddToInventory("Items.Recipe_PowerWeaponMod03",1)
Game.AddToInventory("Items.Recipe_PowerWeaponMod04",1)
Game.AddToInventory("Items.Recipe_PowerWeaponMod05",1)
Game.AddToInventory("Items.Recipe_PowerWeaponMod06",1)
Game.AddToInventory("Items.Recipe_Preset_Achilles_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Ajax_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Ajax_Moron",1)
Game.AddToInventory("Items.Recipe_Preset_Base_Copperhead",1)
Game.AddToInventory("Items.Recipe_Preset_Base_Lexington",1)
Game.AddToInventory("Items.Recipe_Preset_Base_Masamune",1)
Game.AddToInventory("Items.Recipe_Preset_Baseball_Bat_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Burya_Comrade",1)
Game.AddToInventory("Items.Recipe_Preset_Burya_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Carnage_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Copperhead_Genesis",1)
Game.AddToInventory("Items.Recipe_Preset_Crusher_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Defender_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Dian_Yinglong",1)
Game.AddToInventory("Items.Recipe_Preset_Grad_Default",1)
Game.AddToInventory("Items.Recipe_Preset_HMG_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Igla_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Igla_Sovereign",1)
Game.AddToInventory("Items.Recipe_Preset_Kenshin_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Nekomata_Breakthrough_Legendary",1)
Game.AddToInventory("Items.RecipeGrenadeFlashRegular",1)
Game.AddToInventory("Items.RecipeGrenadeFlashHoming",1)
Game.AddToInventory("Items.RecipeGrenadeFragRegular",1)
Game.AddToInventory("Items.RecipeGrenadeFragSticky",1)
Game.AddToInventory("Items.RecipeGrenadeFragHoming",1)
Game.AddToInventory("Items.RecipeGrenadeBiohazardHoming",1)
Game.AddToInventory("Items.RecipeGrenadeBiohazardRegular",1)
Game.AddToInventory("Items.RecipeGrenadeCuttingRegular",1)
Game.AddToInventory("Items.RecipeGrenadeEMPHoming",1)
Game.AddToInventory("Items.RecipeGrenadeEMPRegular",1)
Game.AddToInventory("Items.RecipeGrenadeEMPSticky",1)
Game.AddToInventory("Items.RecipeGrenadeIncendiaryHoming",1)
Game.AddToInventory("Items.RecipeGrenadeIncendiaryRegular",1)
Game.AddToInventory("Items.RecipeGrenadeIncendiarySticky",1)
Game.AddToInventory("Items.RecipeGrenadeReconRegular",1)
Game.AddToInventory("Items.RecipeGrenadeReconSticky",1)
Game.AddToInventory("Items.Recipe_Preset_Nekomata_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Nova_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Nue_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Omaha_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Overture_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Pulsar_Buzzsaw",1)
Game.AddToInventory("Items.Recipe_Preset_Pulsar_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Quasar_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Saratoga_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Satara_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Sidewinder_Divided",1)
Game.AddToInventory("Items.Recipe_Preset_Sor22_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Tactician_Headsman",1)
Game.AddToInventory("Items.Recipe_Preset_Testera_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Tire_Iron_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Unity_Default",1)
Game.AddToInventory("Items.Recipe_Preset_Zhuo_Eight_Star",1)
Game.AddToInventory("Items.Recipe_SimpleFabricEnhancer01",1)
Game.AddToInventory("Items.Recipe_SimpleFabricEnhancer02",1)
Game.AddToInventory("Items.Recipe_SimpleFabricEnhancer03",1)
Game.AddToInventory("Items.Recipe_SimpleFabricEnhancer04",1)
Game.AddToInventory("Items.Recipe_SimpleFabricEnhancer05",1)
Game.AddToInventory("Items.Recipe_SimpleWeaponMod01",1)
Game.AddToInventory("Items.Recipe_SimpleWeaponMod02",1)
Game.AddToInventory("Items.Recipe_SimpleWeaponMod03",1)
Game.AddToInventory("Items.Recipe_SimpleWeaponMod04",1)
Game.AddToInventory("Items.Recipe_SimpleWeaponMod05",1)
Game.AddToInventory("Items.Recipe_SimpleWeaponMod06",1)
Game.AddToInventory("Items.Recipe_SlowRotor",1)
Game.AddToInventory("Items.Recipe_SuicideLvl3Program",1)
Game.AddToInventory("Items.Recipe_SystemCollapseLvl3Program",1)
Game.AddToInventory("Items.Recipe_TakeControlProgram",1)
Game.AddToInventory("Items.Recipe_TechWeaponMod01",1)
Game.AddToInventory("Items.Recipe_TechWeaponMod02",1)
Game.AddToInventory("Items.Recipe_TechWeaponMod04",1)
Game.AddToInventory("Items.Recipe_ThermalDamageCable",1)
Game.AddToInventory("Items.Recipe_ThermalDamageEdge",1)
Game.AddToInventory("Items.Recipe_ThermalDamageKnuckles",1)
Game.AddToInventory("Items.Recipe_ThermalDamageRound",1)
Game.AddToInventory("Items.Recipe_TitaniumPlating",1)
Game.AddToInventory("Items.Recipe_ToggleStateProgram",1)
Game.AddToInventory("Items.Recipe_Tomahawk_Common",1)
Game.AddToInventory("Items.Recipe_w_att_scope_long_01",1)
Game.AddToInventory("Items.Recipe_w_att_scope_long_02",1)
Game.AddToInventory("Items.Recipe_w_att_scope_long_03",1)
Game.AddToInventory("Items.Recipe_w_att_scope_short_01",1)
Game.AddToInventory("Items.Recipe_w_att_scope_short_02",1)
Game.AddToInventory("Items.Recipe_w_att_scope_short_03",1)
Game.AddToInventory("Items.Recipe_w_att_scope_short_04",1)
Game.AddToInventory("Items.Recipe_w_att_scope_sniper_01",1)
Game.AddToInventory("Items.Recipe_w_att_scope_sniper_02",1)
Game.AddToInventory("Items.Recipe_w_melee_hammer2h",1)
Game.AddToInventory("Items.Recipe_w_silencer_01",1)
Game.AddToInventory("Items.Recipe_WeaponMalfunctionProgram",1)
Game.AddToInventory("Items.RecipeBonesMcCoy70V0",1)
Game.AddToInventory("Items.RecipeBonesMcCoy70V1",1)
Game.AddToInventory("Items.RecipeBonesMcCoy70V2",1)
Game.AddToInventory("Items.RecipeFirstAidWhiffV0",1)
Game.AddToInventory("Items.RecipeFirstAidWhiffV1",1)
Game.AddToInventory("Items.RecipeFirstAidWhiffV2",1)
Game.AddToInventory("Items.RecipeGrenadeFlashHoming",1)
Game.AddToInventory("Items.RecipeGrenadeFlashRegular",1)
Game.AddToInventory("Items.RecipeGrenadeFragHoming",1)
Game.AddToInventory("Items.RecipeGrenadeFragRegular",1)
Game.AddToInventory("Items.RecipeGrenadeFragSticky",1)
Game.AddToInventory("Items.ReflexRecorderCommon",1)
Game.AddToInventory("Items.ReflexRecorderLegendary",1)
Game.AddToInventory("Items.ReflexRecorderRare",1)
Game.AddToInventory("Items.ReflexRecorderUncommon",1)
Game.AddToInventory("Items.ReinforcedMusclesEpic",1)
Game.AddToInventory("Items.ReinforcedMusclesRare",1)
Game.AddToInventory("Items.ResistancesBoosterCommon",1)
Game.AddToInventory("Items.ResistancesBoosterEpic",1)
Game.AddToInventory("Items.ResistancesBoosterLegendary",1)
Game.AddToInventory("Items.ResistancesBoosterUncommon",1)
Game.AddToInventory("Items.ReverseMetabolicEnhancer",1)
Game.AddToInventory("Items.ReversePowerInductor",1)
Game.AddToInventory("Items.RoboticCoreCommon",1)
Game.AddToInventory("Items.RoboticCoreEpic",1)
Game.AddToInventory("Items.RoboticCoreLegendary",1)
Game.AddToInventory("Items.RoboticCoreRare",1)
Game.AddToInventory("Items.RoboticCoreUncommon",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Boots",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Glasses",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Jacket",1)
Game.AddToInventory("Items.Rockerboy_01_Set_Pants",1)
Game.AddToInventory("Items.Rockerboy_01_Set_TShirt",1)
Game.AddToInventory("Items.SandevistanC1MK1",1)
Game.AddToInventory("Items.SandevistanC1MK2",1)
Game.AddToInventory("Items.SandevistanC1MK3",1)
Game.AddToInventory("Items.SandevistanC2MK1",1)
Game.AddToInventory("Items.SandevistanC2MK2",1)
Game.AddToInventory("Items.SandevistanC2MK3",1)
Game.AddToInventory("Items.SandevistanC2MK4",1)
Game.AddToInventory("Items.SandevistanC3MK4",1)
Game.AddToInventory("Items.SandevistanC3MK5",1)
Game.AddToInventory("Items.SandevistanC4MK5",1)
Game.AddToInventory("Items.SaratogaRecipe",1)
Game.AddToInventory("Items.SataraRecipe",1)
Game.AddToInventory("Items.ScarfRecipe", 1)
Game.AddToInventory("Items.SeachoRareMKII",1)
Game.AddToInventory("Items.SeachoUncommonMKI",1)
Game.AddToInventory("Items.SecondHeart",1)
Game.AddToInventory("Items.ShingenRecipe",1)
Game.AddToInventory("Items.ShirtRecipe", 1)
Game.AddToInventory("Items.ShortsRecipe", 1)
Game.AddToInventory("Items.SidewinderRecipe",1)
Game.AddToInventory("Items.SimpleFabricEnhancer01", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer02", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer03", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer04", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer05", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer06", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer07", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer09", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer10", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer11", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer12", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer13", 1)
Game.AddToInventory("Items.SimpleFabricEnhancer14", 1)
Game.AddToInventory("Items.SimpleWeaponMod01", 1)
Game.AddToInventory("Items.SimpleWeaponMod02", 1)
Game.AddToInventory("Items.SimpleWeaponMod03", 1)
Game.AddToInventory("Items.SimpleWeaponMod04", 1)
Game.AddToInventory("Items.SimpleWeaponMod08", 1)
Game.AddToInventory("Items.SimpleWeaponMod09", 1)
Game.AddToInventory("Items.SimpleWeaponMod10", 1)
Game.AddToInventory("Items.SimpleWeaponMod11", 1)
Game.AddToInventory("Items.SimpleWeaponMod12", 1)
Game.AddToInventory("Items.SimpleWeaponMod13", 1)
Game.AddToInventory("Items.SimpleWeaponMod16", 1)
Game.AddToInventory("Items.SimpleWeaponMod17", 1)
Game.AddToInventory("Items.SlowRotor",1)
Game.AddToInventory("Items.SmartLinkLegendary",1)
Game.AddToInventory("Items.Sor22Recipe",1)
Game.AddToInventory("Items.StaminaRegenBoosterCommon",1)
Game.AddToInventory("Items.StaminaRegenBoosterEpic",1)
Game.AddToInventory("Items.StaminaRegenBoosterLegendary",1)
Game.AddToInventory("Items.StaminaRegenBoosterRare",1)
Game.AddToInventory("Items.StaminaRegenBoosterUncommon",1)
Game.AddToInventory("Items.StephensonEpicMKIII",1)
Game.AddToInventory("Items.StephensonLegendaryMKIV",1)
Game.AddToInventory("Items.StephensonRareMKII",1)
Game.AddToInventory("Items.StrongArmsEpic",1)
Game.AddToInventory("Items.StrongArmsLegendary",1)
Game.AddToInventory("Items.SubdermalArmorCommon",1)
Game.AddToInventory("Items.SubdermalArmorEpic",1)
Game.AddToInventory("Items.SubdermalArmorLegendary",1)
Game.AddToInventory("Items.SubdermalArmorRare",1)
Game.AddToInventory("Items.SubdermalArmorUncommon",1)
Game.AddToInventory("Items.SynapticAcceleratorCommon",1)
Game.AddToInventory("Items.SynapticAcceleratorEpic",1)
Game.AddToInventory("Items.SynapticAcceleratorLegendary",1)
Game.AddToInventory("Items.SynapticAcceleratorRare",1)
Game.AddToInventory("Items.SynapticAcceleratorUncommon",1)
Game.AddToInventory("Items.TacticianRecipe",1)
Game.AddToInventory("Items.Techie_01_Set_Cap",1)
Game.AddToInventory("Items.Techie_01_Set_Pants",1)
Game.AddToInventory("Items.Techie_01_Set_Shoes",1)
Game.AddToInventory("Items.Techie_01_Set_Tech",1)
Game.AddToInventory("Items.Techie_01_Set_TShirt",1)
Game.AddToInventory("Items.Techie_01_Set_Vest",1)
Game.AddToInventory("Items.TechRecipe", 1)
Game.AddToInventory("Items.TesteraRecipe",1)
Game.AddToInventory("Items.TetratronicEpicMKIII",1)
Game.AddToInventory("Items.TetratronicRareMKII",1)
Game.AddToInventory("Items.TetratronicRipplerLegendaryMKIV",1)
Game.AddToInventory("Items.TetratronicUncommonMKI",1)
Game.AddToInventory("Items.ThermalDamageCable",1)
Game.AddToInventory("Items.ThermalDamageEdge",1)
Game.AddToInventory("Items.ThermalDamageKnuckles",1)
Game.AddToInventory("Items.ThermalDamageRound",1)
Game.AddToInventory("Items.TitaniumInfusedBonesCommon",1)
Game.AddToInventory("Items.TitaniumInfusedBonesRare",1)
Game.AddToInventory("Items.TitaniumInfusedBonesUncommon",1)
Game.AddToInventory("Items.TitaniumPlating",1)
Game.AddToInventory("Items.TranquilizerRound",1)
Game.AddToInventory("Items.TShirtRecipe", 1)
Game.AddToInventory("Items.TygerClawsMantisBladesRotor1",1)
Game.AddToInventory("Items.TygerClawsStrongArmsBattery1",1)
Game.AddToInventory("Items.TygerMeleeWeaponMod", 1)
Game.AddToInventory("Items.TygerRangedWeaponMod", 1)
Game.AddToInventory("Items.TyrosineInjector",1)
Game.AddToInventory("Items.UncommonAjaxRecipe",1)
Game.AddToInventory("Items.UncommonAshuraRecipe",1)
Game.AddToInventory("Items.UncommonBatonRecipe",1)
Game.AddToInventory("Items.UncommonBatRecipe",1)
Game.AddToInventory("Items.UncommonBootsRecipe", 1)
Game.AddToInventory("Items.UncommonBuryaRecipe",1)
Game.AddToInventory("Items.UncommonCapRecipe", 1)
Game.AddToInventory("Items.UncommonCarnageRecipe",1)
Game.AddToInventory("Items.UncommonCasualShoesRecipe", 1)
Game.AddToInventory("Items.UncommonChaoRecipe",1)
Game.AddToInventory("Items.UncommonCopperheadRecipe",1)
Game.AddToInventory("Items.UncommonCrusherRecipe",1)
Game.AddToInventory("Items.UncommonFormalPantsRecipe", 1)
Game.AddToInventory("Items.UncommonFormalShoesRecipe", 1)
Game.AddToInventory("Items.UncommonFormalSkirtRecipe", 1)
Game.AddToInventory("Items.UncommonGlassesRecipe", 1)
Game.AddToInventory("Items.UncommonGradRecipe",1)
Game.AddToInventory("Items.UncommonHatRecipe", 1)
Game.AddToInventory("Items.UncommonJacketRecipe", 1)
Game.AddToInventory("Items.UncommonKenshinRecipe",1)
Game.AddToInventory("Items.UncommonKnifeRecipe",1)
Game.AddToInventory("Items.UncommonLexingtonRecipe",1)
Game.AddToInventory("Items.UncommonMasamuneRecipe",1)
Game.AddToInventory("Items.UncommonMaterial1", 10000000)
Game.AddToInventory("Items.UncommonNekomataRecipe",1)
Game.AddToInventory("Items.UncommonNovaRecipe",1)
Game.AddToInventory("Items.UncommonNueRecipe",1)
Game.AddToInventory("Items.UncommonOmahaRecipe",1)
Game.AddToInventory("Items.UncommonOvertureRecipe",1)
Game.AddToInventory("Items.UncommonPalicaRecipe",1)
Game.AddToInventory("Items.UncommonPantsRecipe", 1)
Game.AddToInventory("Items.UncommonPulsarRecipe",1)
Game.AddToInventory("Items.UncommonQuasarRecipe",1)
Game.AddToInventory("Items.UncommonSaratogaRecipe",1)
Game.AddToInventory("Items.UncommonSataraRecipe",1)
Game.AddToInventory("Items.UncommonScarfRecipe", 1)
Game.AddToInventory("Items.UncommonShingenRecipe",1)
Game.AddToInventory("Items.UncommonShirtRecipe", 1)
Game.AddToInventory("Items.UncommonShortsRecipe", 1)
Game.AddToInventory("Items.UncommonSidewinderRecipe",1)
Game.AddToInventory("Items.UncommonSor22Recipe",1)
Game.AddToInventory("Items.UncommonTacticianRecipe",1)
Game.AddToInventory("Items.UncommonTechRecipe", 1)
Game.AddToInventory("Items.UncommonTesteraRecipe",1)
Game.AddToInventory("Items.UncommonTShirtRecipe", 1)
Game.AddToInventory("Items.UncommonUnityRecipe",1)
Game.AddToInventory("Items.UncommonVestRecipe", 1)
Game.AddToInventory("Items.UncommonVisorRecipe", 1) 
Game.AddToInventory("Items.UncommonYukimuraRecipe",1)
Game.AddToInventory("Items.UnityRecipe",1)
Game.AddToInventory("Items.ValentinosMeleeWeaponMod", 1)
Game.AddToInventory("Items.ValentinosRangedWeaponMod", 1)
Game.AddToInventory("Items.VestRecipe", 1)
Game.AddToInventory("Items.w_att_scope_long_01", 1)
Game.AddToInventory("Items.w_att_scope_long_02", 1)
Game.AddToInventory("Items.w_att_scope_long_03", 1)
Game.AddToInventory("Items.w_att_scope_long_04", 1)
Game.AddToInventory("Items.w_att_scope_short_01", 1)
Game.AddToInventory("Items.w_att_scope_short_02", 1)
Game.AddToInventory("Items.w_att_scope_short_03", 1)
Game.AddToInventory("Items.w_att_scope_short_04", 1)
Game.AddToInventory("Items.w_att_scope_short_05", 1)
Game.AddToInventory("Items.w_att_scope_sniper_01", 1)
Game.AddToInventory("Items.w_att_scope_sniper_02", 1)
Game.AddToInventory("Items.w_silencer_01", 1)
Game.AddToInventory("Items.w_silencer_02", 1)
Game.AddToInventory("Items.w_silencer_03", 1)
Game.AddToInventory("Items.w_silencer_04", 1)
Game.AddToInventory("Items.WeaponMalfunctionLvl2Program",1)
Game.AddToInventory("Items.WeaponMalfunctionLvl2Program",1)
Game.AddToInventory("Items.WeaponMalfunctionLvl3Program",1)
Game.AddToInventory("Items.WeaponMalfunctionLvl3Program",1)
Game.AddToInventory("Items.WeaponMalfunctionLvl4Program",1)
Game.AddToInventory("Items.WeaponMalfunctionLvl4Program",1)
Game.AddToInventory("Items.WeaponMalfunctionProgram",1)
Game.AddToInventory("Items.WeaponMalfunctionProgram",1)
Game.AddToInventory("Items.WhistleLvl2Program",1)
Game.AddToInventory("Items.WhistleLvl3Program",1)
Game.AddToInventory("Items.WhistleProgram",1)
Game.AddToInventory("Items.WraithsMeleeWeaponMod", 1)
Game.AddToInventory("Items.WraithsRangedWeaponMod", 1)
Game.AddToInventory("Items.YukimuraRecipe",1)
Game.AddToInventory("Items.LegendaryChaoRecipe",1)
Game.AddToInventory("Items.LegendaryNueRecipe",1)
Game.AddToInventory("Items.LegendaryOmahaRecipe",1)
Game.AddToInventory("Items.LegendaryUnityRecipe",1)
Game.AddToInventory("Items.LegendaryBatonRecipe",1)
Game.AddToInventory("Items.LegendaryKatanaRecipe",1)
Game.AddToInventory("Items.LegendaryBuryaRecipe",1)
Game.AddToInventory("Items.LegendaryNovaRecipe",1)
Game.AddToInventory("Items.LegendaryMQ008Recipe",1)
Game.AddToInventory("Items.LegendarySor22Recipe",1)
Game.AddToInventory("Items.LegendaryAjaxRecipe",1)
Game.AddToInventory("Items.LegendaryGradRecipe",1)
Game.AddToInventory("Items.LegendaryDianRecipe",1)
Game.AddToInventory("Items.LegendaryZhuoRecipe",1)
Game.AddToInventory("Items.LegendaryIglaRecipe",1)
Game.AddToInventory("Items.LegendaryHMGRecipe",1)
Game.AddToInventory("Items.LegendaryKenshinRecipe",1)
Game.AddToInventory("Items.LegendaryLexingtonRecipe",1)
Game.AddToInventory("Items.LegendaryQ001Recipe",1)
Game.AddToInventory("Items.LegendaryLibertyRecipe",1)
Game.AddToInventory("Items.LegendaryYukimuraRecipe",1)
Game.AddToInventory("Items.LegendaryDefenderRecipe",1)
Game.AddToInventory("Items.LegendaryBaseballRecipe",1)
Game.AddToInventory("Items.LegendaryCrowbarRecipe",1)
Game.AddToInventory("Items.LegendaryIronRecipe",1)
Game.AddToInventory("Items.LegendaryTireRecipe",1)
Game.AddToInventory("Items.LegendaryTomahawkRecipe",1)
Game.AddToInventory("Items.LegendaryCaneRecipe",1)
Game.AddToInventory("Items.LegendaryDildoRecipe",1)
Game.AddToInventory("Items.LegendaryKnifeRecipe",1)
Game.AddToInventory("Items.LegendaryTantoRecipe",1)
Game.AddToInventory("Items.LegendaryKnucklesRecipe",1)
Game.AddToInventory("Items.LegendaryShovelRecipe",1)
Game.AddToInventory("Items.LegendaryKanaboRecipe",1)
Game.AddToInventory("Items.LegendaryHammerRecipe",1)
Game.AddToInventory("Items.LegendaryKukriRecipe",1)
Game.AddToInventory("Items.LegendaryMacheteRecipe",1)
Game.AddToInventory("Items.LegendaryOvertureRecipe",1)
Game.AddToInventory("Items.LegendarySilverhandRecipe",1)
Game.AddToInventory("Items.LegendaryQuasarRecipe",1)
Game.AddToInventory("Items.LegendaryAchillesRecipe",1)
Game.AddToInventory("Items.LegendaryCopperheadRecipe",1)
Game.AddToInventory("Items.LegendaryMasamuneRecipe",1)
Game.AddToInventory("Items.LegendarySidewinderRecipe",1)
Game.AddToInventory("Items.LegendaryAshuraRecipe",1)
Game.AddToInventory("Items.LegendaryNekomataRecipe",1)
Game.AddToInventory("Items.LegendaryPulsarRecipe",1)
Game.AddToInventory("Items.LegendarySaratogaRecipe",1)
Game.AddToInventory("Items.LegendaryShingenRecipe",1)
Game.AddToInventory("Items.LegendaryCrusherRecipe",1)
Game.AddToInventory("Items.LegendaryCarnageRecipe",1)
Game.AddToInventory("Items.LegendaryTacticianRecipe",1)
Game.AddToInventory("Items.LegendarySataraRecipe",1)
Game.AddToInventory("Items.LegendaryPalicaRecipe",1)
Game.AddToInventory("Items.LegendaryTesteraRecipe",1)
Game.AddToInventory("Items.LegendaryPipeWrenchRecipe",1)
Game.AddToInventory("Items.LegendaryButchersRecipe",1)
Game.AddToInventory("Items.LegendaryChefsRecipe",1)
Game.AddToInventory("Items.LegendaryBreakthroughRecipe",1)
